@baseUrl = http://localhost:4000

### Get all jokes
GET {{baseUrl}}

### Add new joke
POST {{baseUrl}}
Content-Type: application/json

{
    "joke": "ทดสอบมุกตลก"
}

### Get joke by id
GET {{baseUrl}}/:id

### Delete joke
DELETE {{baseUrl}}/:id

### Like a joke
POST {{baseUrl}}/:id/like

### Dislike a joke
POST {{baseUrl}}/:id/dislike